# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Ruggiero Guida
# Description of the Site
description: Fighting Climate Change by digitizing the built environment
# URL of Image of the Site
site-image: /WhatATheme/assets/images/mainpage.png
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/2246476/pexels-photo-2246476.jpeg?cs=srgb&dl=pexels-maxime-francis-2246476.jpg&fm=jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: ruggiero.guida@gmail.com
twitter_username: ruggieroguida
linkedin_username: ruggieroguida
# github_username:  rojj
# youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
# reddit_username: /
# behance_username: /
# dribbble_username: /
# spotify_username: /

# Google Analytics
# google-analytics: UA-163806439-1

# Disqus
# disqus-shortname: thedevslot

# Name of the Author
author-name: Ruggiero Guida
# URL for the Image of the Author
author-image: /assets/images/profile.png
# 60 Words About the Author
author-about: Multi-faceted engineer with broad experience in a variety of sustainability related projects in the built environment and now focusing on software, product management and software development. I bring almost 20 years of experience in sustainability and in particular in green buildings, from concept to construction to operation. Currently working at IES Ltd. as Chief Product Manager focusing on digital twins, urban modelling, building operation and outdoor comfort. Co-founder of Virtual Climate Ltd., a software company dedicated to democratize access to complex outdoor comfort analysis on the cloud.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
# author-url: https://github.com/thedevslot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
